name: Lint Code Base

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout
  packages: write

jobs:
  Git-operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Completion Time
        run: |
          git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} | gawk '
          match($0,"^@@ -([0-9]+),([0-9]+) [+]([0-9]+),([0-9]+) @@",a){
            left=a[1]
            ll=length(a[2])
            right=a[3]
            rl=length(a[4])
          }
          /^(---|\+\+\+|[^-+ ])/{ print;next }
          { line=substr($0,2) }
          /^[-]/{ printf "-%"ll"s %"rl"s:%s\n",left++,""     ,line;next }
          /^[+]/{ printf "+%"ll"s %"rl"s:%s\n",""    ,right++,line;next }
                { printf " %"ll"s %"rl"s:%s\n",left++,right++,line }
          ' > git-diff.txt

      - name: Upload git difference
        uses: actions/upload-artifact@v3
        with:
          name: git-diff.txt
          path: git-diff.txt

  lint-operations:
    needs: Git-operations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/download-artifact@master
        with:
          name: git-diff.txt
          path: git-diff.txt

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_LOG_FILE: true
          LOG_FILE: super-linter.log
          LOG_LEVEL: ERROR

      - name: execute py script 
        if: always()
        run: python git-lint.py
