name: invoke issue
on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Omkarprakashchavan/tarun-repo-1/.github/actions@main

