name: Test JFROG Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    outputs:
      jfrog-username: ${{ steps.printcred.outputs.JFROG_USERNAME }}
      jfrog-password: ${{ steps.printcred.outputs.JFROG_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set JFrog Credentials
        id: jfrog-creds
        # uses: ./.github/actions/jfrog-credentials
        uses: githubactions-omkar/repo-3@gh-pages
        with:
          JFROG_URL: "AURBA_URL"
          secrets: ${{ toJson(secrets) }}

      - name: Print JFrog Credentials
        id: printcred
        run: |
          echo "JFROG_USERNAME=$JFROG_USERNAME" >> "$GITHUB_OUTPUT"
          echo "JFROG_PASSWORD=TESTING_SOMETHING" >> "$GITHUB_OUTPUT"
          # echo "JFROG_PASSWORD=$JFROG_PASSWORD" >> "$GITHUB_OUTPUT"
          # echo $JFROG_PASSWORD | sed 's/./& /g'
          echo "JFROG_USERNAME: ${{ steps.jfrog-creds.outputs.JFROG_USERNAME }}"
          echo "JFROG_PASSWORD: ${{ steps.jfrog-creds.outputs.JFROG_PASSWORD }}"
          echo "$JFROG_USERNAME" | sed 's/./& /g'
          echo "$JFROG_PASSWORD" | sed 's/./& /g'

  another-job:
    runs-on: ubuntu-latest
    needs: example-job
    steps:
      - name: run reusable action
        uses: githubactions-omkar/repo-3@gh-pages
        with:
          JFROG_URL: "AURBA_URL"
          secrets: ${{ toJson(secrets) }}
      - name: Print JFrog Credentials
        id: printcred
        run: |
          echo "$JFROG_USERNAME" | sed 's/./& /g'
          echo "$JFROG_PASSWORD" | sed 's/./& /g'

  # job1:
  #   runs-on: ubuntu-latest
  #   # Map a step output to a job output
  #   outputs:
  #     output1: ${{ steps.step1.outputs.test }}
  #     output2: ${{ steps.step2.outputs.test }}
  #   steps:
  #     - id: step1
  #       run: echo "test=hello" >> "$GITHUB_OUTPUT"
  #     - id: step2
  #       run: echo "test=world" >> "$GITHUB_OUTPUT"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.job1.outputs.output1}}
  #         OUTPUT2: ${{needs.job1.outputs.output2}}
  #       run: echo "$OUTPUT1 $OUTPUT2"
