name: Test JFROG Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    outputs:
      jfrog-username: ${{ steps.printcred.outputs.JFROG_USERNAME }}
      jfrog-password: ${{ steps.printcred.outputs.JFROG_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set JFrog Credentials
        id: jfrog-creds
        uses: ./.github/actions/jfrog-credentials
        with:
          JFROG_URL: "AURBA_URL"
          secrets: ${{ toJson(secrets) }}

      - name: Print JFrog Credentials
        id: printcred
        run: |
          echo "JFROG_USERNAME=$JFROG_USERNAME" >> $GITHUB_OUTPUT
          echo "JFROG_PASSWORD=$JFROG_PASSWORD" >> $GITHUB_OUTPUT
          # echo $JFROG_PASSWORD | sed 's/./& /g'
          echo "JFROG_USERNAME: ${{ steps.jfrog-creds.outputs.JFROG_USERNAME }}"
          echo "JFROG_PASSWORD: ${{ steps.jfrog-creds.outputs.JFROG_PASSWORD }}"
          echo "$JFROG_USERNAME" | sed 's/./& /g'
          echo "$JFROG_PASSWORD" | sed 's/./& /g'

  job-2:
    runs-on: ubuntu-latest
    needs: example-job
    steps:
      - name: print secrets
        run: |
          echo "${{ needs.example-job.outputs.jfrog-username }}"
          echo "${{ needs.example-job.outputs.jfrog-password }}"
          export TEST_USERNAME="${{ needs.example-job.outputs.jfrog-username }}"
          echo $TEST_USERNAME
          echo "${{ needs.example-job.outputs.jfrog-username }}" | sed 's/./& /g'
          echo "${{ needs.example-job.outputs.jfrog-password }}" | sed 's/./& /g'
